config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views
from .apps import MainConfig
from django.views.decorators.cache import cache_page

app_name = MainConfig.name

urlpatterns = [
    path("", cache_page(60)(views.StudentListView.as_view()), name="list_student"),
    path("detail/<int:pk>/", views.StudentDetailView.as_view(), name="detail_student"),
    path("create/", views.StudentCreateView.as_view(), name="create_student"),
    path("update/<int:pk>/", views.StudentUpdateView.as_view(), name="update_student"),
    path("delete/<int:pk>/", views.StudentDeleteView.as_view(), name="student_delete"),
]

users/urls.py
from django.urls import path
from .apps import UsersConfig
from django.contrib.auth.views import LoginView, LogoutView
from .views import RegisterView, ProfileView

app_name = UsersConfig.name

urlpatterns = [
    path("", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path(
        "register/",
        RegisterView.as_view(),
        name="register",
    ),
    path("profile/", ProfileView.as_view(), name="profile"),
]

main/models.py
from tkinter.constants import CASCADE

from django.db import models

NULLABLE = {"blank": True, "null": True}


class Student(models.Model):
    # имя, фамилия, аватар
    first_name = models.CharField(max_length=255, verbose_name="Имя")
    last_name = models.CharField(max_length=255, verbose_name="Фамилия")
    avatar = models.ImageField(upload_to="students/", verbose_name="аватар", **NULLABLE)
    email = models.CharField(
        max_length=255, verbose_name="Почта", unique=True, **NULLABLE
    )
    is_active = models.BooleanField(default=True, verbose_name="Активный")

    def __str__(self):
        return self.first_name + " " + self.last_name

    class Meta:
        verbose_name = "Студент"
        verbose_name_plural = "Студенты"
        ordering = ("last_name",)


class Subject(models.Model):
    title = models.CharField(max_length=150, verbose_name="Название")
    description = models.TextField(verbose_name="Описание")

    student = models.ForeignKey(
        Student,
        on_delete=models.CASCADE,
        verbose_name="Студент",
        related_name="subjects",
    )

    def __str__(self):
        return f"{self.title}"

    class Meta:
        verbose_name = "Предмет"
        verbose_name_plural = "Предметы"

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from main.models import NULLABLE


class User(AbstractUser):
    # поле удаляется из родительского класса
    username = None
    email = models.EmailField(unique=True, verbose_name="email")

    phone = models.CharField(max_length=35, verbose_name="Телефон", **NULLABLE)
    avatar = models.ImageField(upload_to="users/", verbose_name="Аватар", **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

main/forms.py
from django.db.models.fields import BooleanField, CharField, TextField, EmailField
from django.forms import ModelForm
from .models import Student, Subject
from django import forms


class StyledFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs["class"] = "form-check-input"
            if (
                isinstance(field, CharField)
                or isinstance(field, EmailField)
                or isinstance(field, TextField)
            ):
                field.widget.attrs["class"] = "form-control"


class StudentForm(StyledFormMixin, ModelForm):
    class Meta:
        fields = "__all__"
        model = Student

    def clean_email(self):
        cleaned_data = self.cleaned_data["email"]

        if not cleaned_data:
            raise forms.ValidationError("Email обязателен для заполнения")

        if "mail.ru" not in cleaned_data:
            raise forms.ValidationError("Почта не относится к домену mail.ru")
        return cleaned_data


class SubjectForm(StyledFormMixin, ModelForm):
    class Meta:
        fields = "__all__"
        model = Subject

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import User
from django import forms


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("email", "password1", "password2")


class UserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            "email",
            "first_name",
            "last_name",
            "phone",
            "avatar",
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["password"].widget = forms.HiddenInput()

main/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.cache import cache
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    ListView,
    UpdateView,
    DetailView,
    DeleteView,
)
from .models import Student, Subject
from .forms import StudentForm, SubjectForm
from django.forms import inlineformset_factory
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from .sevices import get_cached_subjects_for_student


class StudentCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Student
    form_class = StudentForm
    permission_required = "main.add_student"
    success_url = reverse_lazy("main:list_student")


class StudentDetailView(LoginRequiredMixin, DetailView):
    model = Student

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        context_data["subjects"] = get_cached_subjects_for_student(self.object.pk)

        return context_data


class StudentUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Student
    form_class = StudentForm
    permission_required = "main.change_student"
    success_url = reverse_lazy("main:list_student")

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        SubjectFormset = inlineformset_factory(
            Student, Subject, form=SubjectForm, extra=1
        )
        if self.request.method == "POST":
            context_data["formset"] = SubjectFormset(
                self.request.POST, instance=self.object
            )
        else:
            context_data["formset"] = SubjectFormset(instance=self.object)

        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()["formset"]
        self.object = form.save()
        if formset.is_valid():
            # ссылка на родительскую запись
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


class StudentListView(LoginRequiredMixin, ListView):
    model = Student


class StudentDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Student
    success_url = reverse_lazy("main:list_student")
    permission_required = "main.delete_student"

users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView
from users.models import User
from .forms import UserRegistrationForm, UserProfileForm
from django.contrib.auth.mixins import LoginRequiredMixin


class RegisterView(CreateView):
    model = User
    form_class = UserRegistrationForm
    success_url = reverse_lazy("users:login")


class ProfileView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy("users:profile")

    def get_object(self, queryset=None):
        return self.request.user

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru" data-bs-theme="auto">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %} Студенты {% endblock title %}
    </title>
    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/album/">
    <script src="{% static 'js/color-modes.js' %}"></script>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"
          integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB">
    <meta name="theme-color" content="#712cf9">
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select:none
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size:3.5rem
            }
        }

        .b-example-divider {
            width: 100%;
            height: 3rem;
            background-color: #0000001a;
            border: solid rgba(0, 0, 0, .15);
            border-width: 1px 0;
            box-shadow:inset 0 .5em 1.5em #0000001a, inset 0 .125em .5em #00000026
        }

        .b-example-vr {
            flex-shrink: 0;
            width: 1.5rem;
            height:100vh
        }

        .bi {
            vertical-align: -.125em;
            fill:currentColor
        }

        .nav-scroller {
            position: relative;
            z-index: 2;
            height: 2.75rem;
            overflow-y:hidden
        }

        .nav-scroller .nav {
            display: flex;
            flex-wrap: nowrap;
            padding-bottom: 1rem;
            margin-top: -1px;
            overflow-x: auto;
            text-align: center;
            white-space: nowrap;
            -webkit-overflow-scrolling:touch
        }

        .btn-bd-primary {
            --bd-violet-bg: #712cf9;
            --bd-violet-rgb: 112.520718, 44.062154, 249.437846;
            --bs-btn-font-weight: 600;
            --bs-btn-color: var(--bs-white);
            --bs-btn-bg: var(--bd-violet-bg);
            --bs-btn-border-color: var(--bd-violet-bg);
            --bs-btn-hover-color: var(--bs-white);
            --bs-btn-hover-bg: #6528e0;
            --bs-btn-hover-border-color: #6528e0;
            --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
            --bs-btn-active-color: var(--bs-btn-hover-color);
            --bs-btn-active-bg: #5a23c8;
            --bs-btn-active-border-color: #5a23c8
        }

        .bd-mode-toggle {
            z-index:1500
        }

        .bd-mode-toggle .bi {
            width: 1em;
            height:1em
        }

        .bd-mode-toggle .dropdown-menu .active .bi {
            display: block !important
        }
    </style>
</head>
<body>
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"></path>
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"></path>
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"></path>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"></path>
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"></path>
    </symbol>
</svg>
<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center" id="bd-theme" type="button"
            aria-expanded="false" data-bs-toggle="dropdown" aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" aria-hidden="true">
            <use href="#circle-half"></use>
        </svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
    </button>
    <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" aria-hidden="true">
                    <use href="#sun-fill"></use>
                </svg>

                Light
                <svg class="bi ms-auto d-none" aria-hidden="true">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" aria-hidden="true">
                    <use href="#moon-stars-fill"></use>
                </svg>

                Dark
                <svg class="bi ms-auto d-none" aria-hidden="true">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto"
                    aria-pressed="true">
                <svg class="bi me-2 opacity-50" aria-hidden="true">
                    <use href="#circle-half"></use>
                </svg>

                Auto
                <svg class="bi ms-auto d-none" aria-hidden="true">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
    </ul>
</div>
<header data-bs-theme="dark">
    <div class="collapse text-bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4>О студентах </h4>
                    <p class="text-body-secondary">О студентах и их развлечениях</p>
                </div>
                <div class="col-sm-4 offset-md-1 py-4">
                    <ul class="list-unstyled">
                        {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'users:profile' %}" class="btn btn-outline-secondary">Профиль</a>

                            <form method="POST" action="{% url 'users:logout' %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-outline-secondary">Выйти</button>
                            </form>

                        </li>
                        {% else %}
                        <li>
                            <a href="{% url 'users:login' %}" class="btn btn-outline-secondary">Войти</a>
                            <a href="{% url 'users:register' %}" class="btn btn-outline-secondary">Регистрация</a>
                        </li>
                    </ul>

                    {% endif %}

                    <h4>Навигация</h4>
                    <ul class="list-unstyled">
                        <li>
                            <a href="/" class="text-white">Главная</a>
                        </li>


                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
            <a href="#" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor"
                     stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2"
                     viewBox="0 0 24 24">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path>
                    <circle cx="12" cy="13" r="4"></circle>
                </svg>
                <strong>Album</strong>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>
<main>
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">Студенты</h1>

                <a href="{% url 'main:create_student' %}" class="btn btn-primary my-2">Добавить студента</a>
                <a href="#" class="btn btn-secondary my-2">Сделать что-то ещё</a>
                </p>
            </div>
        </div>
    </section>

    {% block content %}
    {% endblock content %}
</main>
<footer class="text-body-secondary py-5">
    <div class="container">
        <p class="float-end mb-1">
            <a href="#">Back to top</a>
        </p>
        <p class="mb-1">Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
        <p class="mb-0">
            New to Bootstrap?
            <a href="/">Visit the homepage</a>
            or read our
            <a href="/docs/5.3/getting-started/introduction">getting started guide</a>
            .
        </p>
    </div>
</footer>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"
        integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI"
        class="astro-vvvwv3sm"></script>
</body>
</html>

templates/main/student_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
Подтверждение удаления
{% endblock title %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-12">
            <form method="post">
                {% csrf_token %}
                <div class="card">
                    <div class="card-header">
                        <h3>Подтверждение удаления</h3>
                    </div>
                    <div class="card-body">
                        <p class="card-text">
                            Вы действительно хотите удалить "{{ object }}" ?
                        </p>
                    </div>
                    <div class="card-footer">
                        <p>
                            <button type="submit" class="btn btn-outline-danger">Удалить</button>
                            <a href="/" class="btn btn-outline-warning">Отмена</a>
                        </p>
                    </div>
                </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/main/student_detail.html
{% extends 'base.html' %}

{% block title %}

{{ object }}

{% endblock title %}

{% block content %}

<div class="container">

    <div class="row">
        <!-- Информация о студенте -->
        <div class="col-8">


            <div class="card">

                <div class="card-header">
                    Информация о {{ object }}
                </div>
                <div class="card-body">
                    {% if object.avatar %}

                    <img src="/media/{{ object.avatar }}" class="img-fluid rounded shadow" alt="фото">

                    {% endif %}

                    <table class="table py-4 table-striped table-hover table-bordered">
                        <tbody>
                        <tr>
                            <td>Имя</td>
                            <td>{{ object.first_name }}</td>
                        </tr>

                        <tr>
                            <td>Фамилия</td>
                            <td>{{ object.last_name }}</td>
                        </tr>

                        <tr>
                            <td>Email</td>
                            <td>

                                {% if object.email %}
                                {{ object.email }}
                                {% else %}
                                Не указан
                                {% endif %}

                            </td>
                        </tr>
                        <tr>
                            <td>Активность</td>
                            <td>
                                {% if object.is_active %}
                                Да
                                {% else %}
                                Нет
                                {% endif %}
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <div class="card-footer">
                    <p>
                        <a href="{% url 'main:update_student' object.pk %}" class="btn btn-warning">Редактировать</a>
                        {% if perma.main.delete_student %}

                        <a href="{% url 'main:student_delete' object.pk %}" class="btn btn-danger">Удалить</a>
                        {% endif %}


                        <a href="{% url 'main:list_student' %}" class="btn btn-primary">Назад к списку</a>
                    </p>
                </div>


            </div>


        </div>

        <!-- Информация о предметах студента -->
        <div class="col-4">


            <div class="card">

                <div class="card-header">
                    Предметы студента <em> {{ object }} </em>
                </div>
                <div class="card-body">

                    <table class="table py-4 table-striped table-hover table-bordered">
                        <tbody>

                        {% for subject in subjects %}
                        <tr>
                            <td>{{ subject.title }}</td>

                            <td>{{ subject.description }}</td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="card-footer">
                </div>


            </div>


        </div>


    </div>

</div>

{% endblock content %}

templates/main/student_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %} Добавление студента {% endblock title %}

{% block content %}
<form method="post" enctype="multipart/form-data">


    <div class="container">
        <div class="row">
            <div class="col-8">
                <div class="card">
                    <div class="card-header">
                        <h2 class="card-title">
                            {% if object %}
                            Редактирование
                            {% else %}
                            Добавление
                            {% endif %}
                            студента
                        </h2>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-outline-success">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </div>
                </div>
            </div>

            {% if object %}
            <div class="col-4">
                <div class="card">
                    <div class="card-header">
                        <h2 class="card-title">Предметы студента</h2>
                    </div>
                    <div class="card-body">
                        {{ formset.management_form }}
                        {% for form in formset.forms %}
                        {{ form|crispy }}
                        {% endfor %}
                    </div>
                    <div class="card-footer"></div>
                </div>
            </div>
            {% endif %}


        </div>

</form>


{% endblock content %}

templates/main/student_list.html
{% extends 'base.html' %}

{% block title %} Все студенты {% endblock title %}

{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

            {% for student in object_list %}
            <div class="col">
                <div class="card shadow-sm">
                    {% if student.avatar %}
                    <img src="media/{{ student.avatar }}" alt="фото">
                    {% else %}
                    <svg width="100%" height="100%" viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg"
                         preserveAspectRatio="xMidYMid meet">
                        <rect width="100%" height="100%" fill="#e0e0e0"/>
                        <text x="50%" y="50%" font-family="Arial, sans-serif" font-size="80" fill="#999"
                              text-anchor="middle" dy="0.35em">?
                        </text>
                    </svg>
                    {% endif %}

                    <div class="card-body">
                        <p class="card-text">
                            {{ student.first_name }} {{ student.last_name }}


                        </p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <p>
                                    <a href="{% url 'main:detail_student'  student.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Посмотреть</a>
                                    <a href="{% url 'main:update_student' student.pk %}" type="button"
                                       class="btn btn-sm btn-outline-secondary">Редактировать</a>
                                    {% if perms.main.delete_student %}
                                    <a href="{% url 'main:student_delete' student.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Удалить</a>
                                    {% endif %}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}

        </div>
    </div>
</div>

{% endblock content %}

templates/users/user_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}


{% block title %}
{% if user.is_authenticated %}
Профиль
{% else %}
Регистрация
{% endif %}
{% endblock title %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-12">

            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            {% if user.is_authenticated %}
                            Профиль
                            {% else %}
                            Регистрация
                            {% endif %}


                        </h3>
                    </div>
                    <div class="card-body">
                        {{ form | crispy }}

                    </div>

                    <div class="card-footer">
                        <button type='submit' class="btn btn-outline-success">
                            {% if user.is_authenticated %}
                            Сохранить изменения
                            {% else %}
                            Зарегистрироваться
                            {% endif %}
                        </button>
                    </div>
                </div>

            </form>

        </div>
    </div>
</div>


{% endblock content %}